project:
  type: website
  output-dir: docs

website:
  title: "STA9750 Submission Material"
  navbar:
    left:
      - text: "About Me"
        href: index.qmd
      - text: "NYC Payroll Data Analysis"
        href: mp01.qmd
      - text: "Grand Transit Awards: GTA IV Edition"
        href: mp02.qmd
      - text: "Ultimate Playlist: Hustle and Heart"
        href: mp03.qmd
      - text: "MP04: County-Level U.S. Election Analysis (2020 vs 2024)"
        href: mp04.qmd
      - text: "Final Project: Subway Metrics"
        href: Subway_Metrics.qmd

format:
  html:
    toc: true
    toc-depth: 4
    smooth-scroll: true
    css: []   # ❗ no global css, each page attaches its own

# ship all CSS + images to docs/
resources:
  - styles
  - images

