name: Build and Deploy Pages (Quarto)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false     # ✅ stop fetching submodules
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Optional: install R & needed packages if your qmd uses R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # If you need R packages, add a step here to install them

      - name: Render site with Quarto
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs  # Quarto’s default render output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
